import pandas as pd
import matplotlib.pyplot as plt
# 读取 CSV 文件
data0 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.002.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.01.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.05.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data3 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.3.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['R_t'],color='green',linestyle = ":", label='p2=0.002')
plt.plot(data1['t'], data1['R_t'],color='red',linestyle = "--", label='p2=0.01')
plt.plot(data2['t'], data2['R_t'],color='blue',linestyle = "-.", label='p2=0.05')
plt.plot(data3['t'], data3['R_t'],color='black',linestyle = "-.", label='p2=0.3')
plt.xlabel('Time (t)')
plt.ylabel('R-Probability')
plt.title('glob_dissemination_of_p1')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.002.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.01.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.05.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data3 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.3.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['S_i'],color='green',linestyle = ":", label='p2=0.002')
plt.plot(data1['t'], data1['S_i'],color='red',linestyle = "--", label='p2=0.01')
plt.plot(data2['t'], data2['S_i'],color='blue',linestyle = "-.", label='p2=0.05')
plt.plot(data3['t'], data3['S_i'],color='black',linestyle = "-.", label='p2=0.3')
plt.xlabel('Time (t)')
plt.ylabel('SI-Probability')
plt.title('glob_dissemination_of_p1')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.002.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.01.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.05.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data3 = pd.read_csv('C:\Users\98704\Desktop\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.3.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['S_a'],color='green',linestyle = ":", label='p2=0.002')
plt.plot(data1['t'], data1['S_a'],color='red',linestyle = "--", label='p2=0.01')
plt.plot(data2['t'], data2['S_a'],color='blue',linestyle = "-.", label='p2=0.05')
plt.plot(data3['t'], data3['S_a'],color='black',linestyle = "-.", label='p2=0.3')
plt.xlabel('Time (t)')
plt.ylabel('Sa-Probability')
plt.title('glob_dissemination_of_p1')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.002.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.01.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.05.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data3 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.3.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['E_t'],color='green',linestyle = ":", label='p2=0.002')
plt.plot(data1['t'], data1['E_t'],color='red',linestyle = "--", label='p2=0.01')
plt.plot(data2['t'], data2['E_t'],color='blue',linestyle = "-.", label='p2=0.05')
plt.plot(data3['t'], data3['E_t'],color='black',linestyle = "-.", label='p2=0.3')
plt.xlabel('Time (t)')
plt.ylabel('Et-Probability')
plt.title('glob_dissemination_of_p1')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.002.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.01.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.05.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data3 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model_p2=0.3.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['I_t'],color='green',linestyle = ":", label='p2=0.002')
plt.plot(data1['t'], data1['I_t'],color='red',linestyle = "--", label='p2=0.01')
plt.plot(data2['t'], data2['I_t'],color='blue',linestyle = "-.", label='p2=0.05')
plt.plot(data3['t'], data3['I_t'],color='black',linestyle = "-.", label='p2=0.3')
plt.xlabel('Time (t)')
plt.ylabel('It-Probability')
plt.title('glob_dissemination_of_p1')
plt.legend()
plt.grid(True)

plt.show()