import pandas as pd
import matplotlib.pyplot as plt

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=3.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=5.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=7.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['S_i'],color='blue',linestyle = "--",  label='m2=3')
plt.plot(data1['t'], data1['S_i'],color='red',linestyle = "-",  label='m2=5')
plt.plot(data2['t'], data2['S_i'],color='green',linestyle = ":",  label='m2=7')
plt.xlabel('Time (t)')
plt.ylabel('Density')
plt.title('Si')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=3.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=5.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=7.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['S_a'],color='blue',linestyle = "--",  label='m2=3')
plt.plot(data1['t'], data1['S_a'],color='red',linestyle = "-",  label='m2=5')
plt.plot(data2['t'], data2['S_a'],color='green',linestyle = ":",  label='m2=7')
plt.xlabel('Time (t)')
plt.ylabel('Density')
plt.title('Sa')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=3.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=5.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=7.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['E_t'],color='blue',linestyle = "--",  label='m2=3')
plt.plot(data1['t'], data1['E_t'],color='red',linestyle = "-",  label='m2=5')
plt.plot(data2['t'], data2['E_t'],color='green',linestyle = ":",  label='m2=7')
plt.xlabel('Time (t)')
plt.ylabel('Density')
plt.title('E')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=3.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=5.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=7.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['I_t'],color='blue',linestyle = "--",  label='m2=3')
plt.plot(data1['t'], data1['I_t'],color='red',linestyle = "-",  label='m2=5')
plt.plot(data2['t'], data2['I_t'],color='green',linestyle = ":",  label='m2=7')
plt.xlabel('Time (t)')
plt.ylabel('Density')
plt.title('I')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=3.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=5.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data2 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new_m2=7.0.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['R_t'],color='blue',linestyle = "--",  label='m2=3')
plt.plot(data1['t'], data1['R_t'],color='red',linestyle = "-",  label='m2=5')
plt.plot(data2['t'], data2['R_t'],color='green',linestyle = ":",  label='m2=7')
plt.xlabel('Time (t)')
plt.ylabel('Density')
plt.title('R')
plt.legend()
plt.grid(True)

plt.show()