import pandas as pd
import matplotlib.pyplot as plt

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['S_i'],color='black',linestyle = "--",  label='lilun_S_i')
plt.plot(data1['t'], data1['S_i'],color='red',linestyle = "-",  label='fangzhen_S_i')
plt.xlabel('Time (t)')
plt.ylabel('Probability')
plt.title('SEIIR_Si')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['S_a'],color='black',linestyle = "--",  label='lilun_S_a')
plt.plot(data1['t'], data1['S_a'],color='red',linestyle = "-",  label='fangzhen_S_a')
plt.xlabel('Time (t)')
plt.ylabel('Probability')
plt.title('SEIIR_Sa')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['E_t'],color='black',linestyle = "--",  label='lilun_E_t')
plt.plot(data1['t'], data1['E_t'],color='red',linestyle = "-",  label='fangzhen_E_t')
plt.xlabel('Time (t)')
plt.ylabel('Probability')
plt.title('SEIIR_E')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['I_t'],color='black',linestyle = "--",  label='lilun_I_t')
plt.plot(data1['t'], data1['I_t'],color='red',linestyle = "-",  label='fangzhen_I_t')
plt.xlabel('Time (t)')
plt.ylabel('Probability')
plt.title('SEIIR_I')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['R_t'],color='black',linestyle = "--",  label='lilun_R_t')
plt.plot(data1['t'], data1['R_t'],color='red',linestyle = "-",  label='fangzhen_R_t')
plt.xlabel('Time (t)')
plt.ylabel('Probability')
plt.title('SEIIR_R')
plt.legend()
plt.grid(True)

# 读取 CSV 文件
data0 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Function_model_new.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
data1 = pd.read_csv('D:\\桌面\\Hypernetwork_information_model\\SEIIR_output\\SEIIR_Hypernetwork_model.txt', header=None, names=['t', 'S_i','S_a',  'E_t','I_t','R_t'])
plt.figure(figsize=(10, 6))
plt.plot(data0['t'], data0['S_i'],color='black',linestyle = "--",  label='lilun_S_i')
plt.plot(data1['t'], data1['S_i'],color='red',linestyle = ":",  label='fangzhen_S_i')
plt.plot(data0['t'], data0['S_a'],color='black',linestyle = "--",  label='lilun_S_a')
plt.plot(data1['t'], data1['S_a'],color='red',linestyle = ":",  label='fangzhen_S_a')
plt.plot(data0['t'], data0['E_t'],color='black',linestyle = "--",  label='lilun_E_t')
plt.plot(data1['t'], data1['E_t'],color='red',linestyle = ":",  label='fangzhen_E_t')
plt.plot(data0['t'], data0['I_t'],color='black',linestyle = "--",  label='lilun_I_t')
plt.plot(data1['t'], data1['I_t'],color='red',linestyle = ":",  label='fangzhen_I_t')
plt.plot(data0['t'], data0['R_t'],color='black',linestyle = "--",  label='lilun_R_t')
plt.plot(data1['t'], data1['R_t'],color='red',linestyle = ":",  label='fangzhen_R_t')
plt.xlabel('Time (t)')
plt.ylabel('Probability')
plt.title('SEIIR_R')
plt.legend()
plt.grid(True)

plt.show()
